# Top level styles
StylesPath=.github/vale
MinAlertLevel = suggestion
IgnoredScopes = code, tt, img, url, a
SkippedScopes = script, style, pre, figure, code, comment.line, comment.block

# Vocabularies
Vocab = Mintlify, PowerSync

# This is required since Vale doesn't officially support MDX
[formats]
mdx = md

# MDX support
[*.mdx]
BasedOnStyles = Vale
Vale.Terms = NO # Enforces really harsh capitalization rules, keep off

TokenIgnores = (?sm)((?:import|export) .+?$), \
(?<!`)(<\w+ ?.+ ?\/>)(?!`), \
(<[A-Z]\w+>.+?<\/[A-Z]\w+>), \
(``[^`]+``), \
(`[^`]+`), \
(_[A-Za-z][^_\n]*?_)

# Exclude fenced code blocks (including indented ones inside JSX) and JSX:
BlockIgnores = (?sm)^\s*```[\s\S]*?^\s*```\s*$, \
(?sm)^(<\w+\n .*\s\/>)$, \
(?sm)^({.+.*})

CommentDelimiters = {/*, */}