name: Check Documentation

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  check:
    name: Check Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # This checks internal links, but does not validate external links
      - name: Check for broken links
        run: pnpm check:links
